refactor: remove BuildState.make_named_temporary method
This method was unused, and, anyway, was broken.  (Its
`os.urandom(20).encode("hex")` throws `"AttributeError: 'bytes' object
has no attribute 'encode'"`.)

This also eliminates the need for BuildState to implement the context
manager API.