fix(pre-commit): fix node tests
These were failing with:

  AssertionError: `language: node` must have package.json or additional_dependencies

Looking at pre-commit code, I have no idea how this every worked with
`language: node`.  Pre-commit is trying to find a package.json so that
it can install dependencies (but seems to only be able to find a
package.json in the top-level directory, which ours is not).

Anyway, we install our npm dependencies manually and just run eslint
and prettier as scripts.